### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by r-akemii** [AequilibraE/qaequilibrae#265]
Based on the addition of coverage reports on #262. 

The improvement of the following modules should increase the overall coverage:

- [x] Distribution procedures (wait for #254, #260)
- [x] GIS / Desire lines
- [x] GIS / Stacked bandwidth
- [x] GIS / Scenario Comparison
- [x] Project / Add zoning data
- [x] Project / Create Project from layers
- [ ] Project / Create Project from OSM
- [x] Network Manipulation / Network preparation (#316)
- [x] Network Manipulation / Add centroid connectors (wait for #257)
- [x] Routing procedures / TSP
